# Generated by Django 5.2.3 on 2026-07-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencestep',
            name='delay_position',
            field=models.CharField(choices=[('before', '동작 전'), ('after', '동작 후')], default='after', max_length=10),
        ),
    ]
