# Generated by Django 5.2.3 on 2026-07-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotcore', '0002_sequencestep_delay_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='protocol',
            field=models.CharField(choices=[('ir', 'IR'), ('tuya', 'Tuya'), ('zigbee', 'Zigbee')], default='ir', max_length=20),
        ),
    ]
