# Generated by Django 5.2.3 on 2025-06-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controller',
            options={'permissions': [('can_control_iot_devices', 'Can control IoT devices')]},
        ),
    ]
