# Generated by Django 5.2.3 on 2025-07-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcore', '0002_alter_controller_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='device_type',
            field=models.CharField(default='temp_device', max_length=50),
            preserve_default=False,
        ),
    ]
