# Generated by Django 5.2.3 on 2025-11-08 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcore', '0003_controller_device_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='device_type',
        ),
        migrations.AddField(
            model_name='controller',
            name='device',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_set_ai', to='smartcore.controller'),
        ),
    ]
