# Generated by Django 5.2.3 on 2025-11-09 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcore', '0004_remove_controller_device_type_controller_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='controller',
        ),
        migrations.AlterField(
            model_name='controller',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controller', to='smartcore.device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
