# Generated by Django 5.2.3 on 2025-11-09 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcore', '0005_remove_device_controller_alter_controller_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_id',
        ),
        migrations.AddField(
            model_name='device',
            name='device_uid',
            field=models.CharField(default='aircon_1', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controller',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controllers', to='smartcore.device'),
        ),
    ]
