# Generated by Django 5.2.3 on 2025-11-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcore', '0006_remove_device_device_id_device_device_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.CharField(default='aircon_1', max_length=100),
            preserve_default=False,
        ),
    ]
