# Generated by Django 5.2.3 on 2025-11-09 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcore', '0007_device_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='controller',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_device', to='smartcore.controller'),
        ),
    ]
