# Generated by Django 5.2.3 on 2026-06-05 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcore', '0008_device_controller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='controller',
        ),
        migrations.AlterField(
            model_name='controller',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controller', to='smartcore.device'),
        ),
    ]
