# Generated by Django 5.2.3 on 2026-08-01 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotcore', '0003_device_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger_type', models.CharField(choices=[('once', '한 번'), ('daily', '매일'), ('weekly', '매주'), ('interval', '일정 간격')], max_length=20)),
                ('trigger_config', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_run_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SequenceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('manual', '수동'), ('schedule', '스케줄'), ('mqtt', 'MQTT')], max_length=20)),
                ('status', models.CharField(choices=[('pending', '대기'), ('running', '실행 중'), ('success', '성공'), ('failed', '실패'), ('cancelled', '취소')], db_index=True, default='pending', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SequenceStepRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('action_code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('running', '실행 중'), ('success', '성공'), ('failed', '실패'), ('skipped', '건너뜀')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.AddField(
            model_name='sequencestep',
            name='target_type',
            field=models.CharField(choices=[('device', '장치'), ('system', '시스템')], default='device', max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='protocol',
            field=models.CharField(choices=[('ir', 'IR'), ('tuya', 'Tuya'), ('zigbee', 'Zigbee'), ('tcpip', 'TCP/IP'), ('mqtt', 'MQTT')], default='ir', max_length=20),
        ),
        migrations.AlterField(
            model_name='sequencestep',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iotcore.device'),
        ),
        migrations.AddConstraint(
            model_name='sequencestep',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('device__isnull', False), ('target_type', 'device')), models.Q(('device__isnull', True), ('target_type', 'system')), _connector='OR'), name='sequence_step_target_matches_device'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='iotcore.sequence'),
        ),
        migrations.AddField(
            model_name='sequencerun',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='iotcore.schedule'),
        ),
        migrations.AddField(
            model_name='sequencerun',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='iotcore.sequence'),
        ),
        migrations.AddField(
            model_name='sequencesteprun',
            name='sequence_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_runs', to='iotcore.sequencerun'),
        ),
        migrations.AddField(
            model_name='sequencesteprun',
            name='sequence_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='iotcore.sequencestep'),
        ),
        migrations.AddConstraint(
            model_name='sequencerun',
            constraint=models.UniqueConstraint(fields=('schedule', 'scheduled_for'), name='unique_schedule_run_time'),
        ),
    ]
