# Generated by Django 5.2.3 on 2026-09-11 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotcore', '0025_simple_automation_core'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationrun',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterField(
            model_name='actionrun',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('running', '실행 중'), ('success', '성공'), ('failed', '실패'), ('cancelled', '취소'), ('skipped', '건너뜀')], max_length=20),
        ),
        migrations.AlterField(
            model_name='automationrun',
            name='automation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='iotcore.automation'),
        ),
        migrations.AlterField(
            model_name='automationrun',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('running', '실행 중'), ('success', '성공'), ('failed', '실패'), ('cancelled', '취소'), ('skipped', '건너뜀')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='step',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='iotcore.automation'),
        ),
    ]
