# Generated by Django 5.2.3 on 2026-09-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotcore', '0029_actionrun_scheduled_for'),
        ('iotcore', '0029_device_action_queue'),
    ]

    operations = [
    ]
