# Generated by Django 5.2.3 on 2026-09-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotcore', '0030_merge_20260920_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionrun',
            name='scheduled_for',
        ),
    ]
