"""
Django settings for playground project.

Generated by 'django-admin startproject' using Django 3.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

import os, my_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = my_settings.SECRET_KEY('secret')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
# DEBUG = True

# MQTT 테스트 용 장고 서버 IP주소
MQTT_HOST = "127.0.0.1"   # IoT 서버 IP
MQTT_PORT = 1883

# Dashboard system-node monitoring
IOTCORE_AI_NODE_UID = "home-ai-main"
IOTCORE_PI5_NODE_UID = "pi5"
NODE_TELEMETRY_OFFLINE_SECONDS = 5
NODE_METRIC_RETENTION_HOURS = 24

# Music Assistant 로컬 API
MUSIC_ASSISTANT_URL = "http://192.168.0.14:8095"
MUSIC_ASSISTANT_TOKEN = os.environ.get(
    "MUSIC_ASSISTANT_TOKEN", 
    SECRET_KEY
)
MUSIC_ASSISTANT_TIMEOUT = 30

ALLOWED_HOSTS = [
    "211.209.134.102",
    "192.168.0.8",
    "localhost",
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "common",
    "board",
    "iotcore",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = "playground.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "TEMPLATES"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "playground.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

NAME, USER, PASSWORD, HOST, PORT = my_settings.db_items()
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # MariaDB를 사용할 경우 mysql 엔진 사용
        'NAME': NAME,          # MariaDB에 생성된 데이터베이스 이름
        'USER': USER,          # MariaDB 사용자 이름
        'PASSWORD': PASSWORD,  # MariaDB 사용자 비밀번호
        'HOST': HOST,                # MariaDB 서버 IP 주소
        'PORT': PORT,                        # MariaDB 서버 포트 (기본값 3306)
    }
}
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'STATIC')
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / 'staticfiles'
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# 로그인 성공 후 이동하는 URL
LOGIN_REDIRECT_URL = '/'
